#ifndef LANG_H
#define LANG_H

static int lang;

char *getLangString(int target);

char *getCountryString(int target);

void setCurrentLang(int value)
{

    if (value >= 0 && value <= 5)
    {
        lang = value;
    }
}

char *gs(const char *targetString)
{

    int i = 0;

    while (strcmp(getLangString(i), "ARRAY_END") != 0)
    {

        if (!strcmp(targetString, getLangString(i)))
        {
            return getLangString(i + lang);
        }

        i++;
    }

    return "NOT_FOUND";
}

char *gcs(const char *targetString)
{

    int i = 0;

    while (strcmp(getCountryString(i), "ARRAY_END") != 0)
    {

        if (!strcmp(targetString, getCountryString(i)))
        {
            return getCountryString(i + lang);
        }

        i++;
    }

    return "NOT_FOUND";
}

void getCountryTab(const char *targetString, char tab[6][40], int size)
{

    int i = 0;
    int actualSize = 0;

    while (strcmp(getCountryString(i), "ARRAY_END") != 0 && actualSize < size)
    {

        if (strstr(getCountryString(i), targetString) != NULL && i == ((i / 6) * 6) + lang)
        {
            strcpy(tab[actualSize], getCountryString(i - lang));
            actualSize++;
        }

        i++;
    }

    for (int i = actualSize; i < size; ++i)
    {
        strcpy(tab[i], "");
    }
}

char *getLangString(int target)
{

    char *const langStrings[] =
        {
            "Battleship",
            "Bataille Navale",
            "Batalla naval",
            "Navio de guerra",
            "Schlachtschiff",
            "Corazzata",

            "Home",
            "Accueil",
            "Recepción",
            "Casa",
            "Zuhause",
            "Accoglienza",

            "Scores",
            "Scores",
            "Puntuaciones",
            "Pontuações",
            "Ergebnis",
            "Punto",

            "Settings",
            "Paramètres",
            "Ajustes",
            "Configurações",
            "Die Einstellungen",
            "Impostazioni",

            "Settings",
            "Paramètres",
            "Ajustes",
            "Configurações",
            "Die Einstellungen",
            "Impostazioni",

            "Statistics",
            "Statistiques",
            "Estadísticas",
            "Estatisticas",
            "Statistiken",
            "Statistiche",

            "Credits",
            "Crédits",
            "Créditos",
            "Créditos",
            "Hommagen",
            "Crediti",

            "Nickname",
            "Pseudo",
            "Apodo",
            "Apelido",
            "Spitzname",
            "Soprannome",

            "Best Time",
            "Meilleur temps",
            "Mejor época",
            "Melhor tempo",
            "Beste Zeit",
            "Miglior tempo",

            "Choose a lang to continue",
            "Choisissez une langue pour continuer",
            "Elija un idioma para continuar",
            "Escolha um idioma para continuar",
            "Wählen Sie eine Sprache, um fortzufahren",
            "Scegli una lingua per continuare",

            "Continue",
            "Continuer",
            "Seguir",
            "Continuar",
            "Fortsetzen",
            "Continua",

            "Welcome/aboard !",
            "Bienvenue/à bord !",
            "Bienvenidos/a bordo !",
            "Bem vindo/a bordo !",
            "Willkommen/an Bord !",
            "Benvenuto/a bordo !",

            "Average Time",
            "Temps moyen",
            "Tiempo promedio",
            "Tempo médio",
            "Durchschnittliche Zeit",
            "Tempo medio",

            "First connection",
            "Première connexion",
            "Primera conexión",
            "Primeira conexão",
            "Erste Verbindung",
            "Primo collegamento",

            "Ratio  V / D",
            "Rapport V / D",
            "Relación V / D",
            "Razão V / D",
            "Verhältnis V / D.",
            "Rapporto V / D",

            "Victories",
            "Victoires",
            "Victorias",
            "Vitórias",
            "Siege",
            "Vittorie",

            "Display",
            "Affichage",
            "Monitor",
            "Exibição",
            "Anzeige",
            "Schermo",

            "Interface",
            "Interface",
            "Interfaz",
            "Interface",
            "Schnittstelle",
            "Interfaccia",

            "Sounds",
            "Sons",
            "Sonidos",
            "Geräusche",
            "Siege",
            "Suoni",

            "Profile",
            "Profil",
            "Perfil",
            "Perfil",
            "Profil",
            "Profilo",

            "FullScreen",
            "Plein écran",
            "Pantalla completa",
            "Tela cheia",
            "Ganzer Bildschirm",
            "Schermo intero",

            "FullScreen-Windowed",
            "Plein écran fenêtré",
            "Pantalla completa con ventana",
            "Tela inteira com janela",
            "Vollbildfenster",
            "Schermo intero con finestra",

            "Windowed",
            "Fenêtré",
            "Ventana",
            "Com janela",
            "Fenster",
            "Finestrato",

            "English",
            "Anglais",
            "Inglés",
            "Inglês",
            "Englisch",
            "Inglese",

            "French",
            "Français",
            "Francés",
            "Francês",
            "Französisch",
            "Francese",

            "Spanish",
            "Espagnol",
            "Español",
            "Espanhol",
            "Spanisch",
            "Spagnolo",

            "Portuguese",
            "Portugais",
            "Portugués",
            "Português",
            "Portugiesisch",
            "Portoghese",

            "German",
            "Allemand",
            "Alemán",
            "Alemão",
            "Deutsche",
            "Tedesco",

            "Italian",
            "Italien",
            "Italiano",
            "Italiano",
            "Italienisch",
            "Italiano",

            "Apply",
            "Appliquer",
            "Aplicar",
            "Aplique",
            "Anwenden",
            "Applicare",

            "Play",
            "Jouer",
            "Jugar",
            "Jogar",
            "Abspielen",
            "Giocare",

            "Customized",
            "Personnalisé",
            "Personalizado",
            "Personalizado",
            "Angepasst",
            "Personalizzato",

            "Easy",
            "Facile",
            "Fácil",
            "Fácil",
            "Einfach",
            "Facile",

            "Medium",
            "Moyen",
            "Medio",
            "Médio",
            "Mittel",
            "Medio",

            "Difficult",
            "Difficile",
            "difícil",
            "difícil",
            "Schwer",
            "Difficile",

            "Competitive",
            "Compétitif",
            "Competitivo",
            "Competitivo",
            "Wettbewerbsfähig",
            "Competitivo",

            "AI intelligence level",
            "Niveau d'intelligence IA",
            "Nivel de inteligencia de IA",
            "Nível de inteligência AI",
            "KI-Intelligenzstufe",
            "Livello di intelligenza AI",

            "Max number of strokes per round",
            "Nombre maximum de coups par tour",
            "Número máximo de golpes por ronda",
            "Número máximo de tacadas por rodada",
            "Maximale Anzahl von Schlägen pro Runde",
            "Numero massimo di colpi per round",

            "The",
            "Bataille",
            "Los",
            "Navio De",
            "Das",
            "Il",

            "BattleShip",
            "Navale",
            "Acorazado",
            "Guerra",
            "Schlachtschiff",
            "Corazzata",

            "By",
            "Par",
            "Por",
            "Por",
            "Mit dem",
            "Di",

            "New game",
            "Nouvelle partie",
            "Nuevo juego",
            "Novo jogo",
            "Neues Spiel",
            "Nuovo gioco",

            "Create new game",
            "Créer une nouvelle Partie",
            "Crear juego nuevo",
            "Criar Novo Jogo",
            "Neues Spiel erstellen",
            "Crea nuovo gioco",

            "New game",
            "Nouvelle partie",
            "Nuevo juego",
            "Novo jogo",
            "Neues Spiel",
            "Nuovo gioco",

            "Phase 1/The placement",
            "Phase 1/Le placement",
            "Fase 1/La colocación",
            "Fase 1/A colocação",
            "Phase 1/Die Platzierung",
            "Fase 1/Il posizionamento",

            "Phase 2/The fight",
            "Phase 2/Le combat",
            "Fase 2/La pelea",
            "Fase 2/A luta",
            "Phase 2/Der Kampf",
            "Fase 2/La lotta",

            "Missed !",
            "Raté !",
            "Perdido !",
            "Perdido ! ",
            "Vermisst !",
            "Perse !",

            "Hit !",
            "Touché !",
            "Golpear !",
            "Acertar !",
            "Schlagen !",
            "Colpire !",

            "Sunk !",
            "Coulé !",
            "Hundido !",
            "Afundado !",
            "Versunken !",
            "Affondato !",

            "Aircraft Carrier",
            "Porte-avions",
            "Portaaviones",
            "Porta-aviões",
            "Flugzeugträger",
            "Portaerei",

            "Submarine",
            "Sous-marin",
            "Submarino",
            "Submarino",
            "U-Boot",
            "Sottomarino",

            "Cruiser",
            "Croiseur",
            "Crucero",
            "Crucero",
            "Kreuzer",
            "Incrociatore",

            "Torpedo boat",
            "Torpilleur",
            "Barco torpedo",
            "Barco torpedeiro",
            "Torpedoboot",
            "Torpediniera",

            "Counter torpedo boat",
            "Contre torpilleur",
            "Barco torpedo contador",
            "Barco torpedeiro contador",
            "Gegen Torpedoboot",
            "Contro torpediniera",

            "Validate",
            "Valider",
            "Validar",
            "Validar",
            "Bestätigen",
            "Convalidare",

            "times",
            "fois",
            "veces",
            "vezes",
            "mal",
            "volte",

            "The AI played :",
            "L'IA a joué :",
            "La IA jugó :",
            "O AI jogou :",
            "Die KI spielte :",
            "L'IA ha giocato :",

            "Total time",
            "Temps total",
            "Tiempo Total",
            "Tempo total",
            "Gesamtzeit",
            "Tempo totale",

            "You",
            "Vous avez",
            "Habéis",
            "Você",
            "Du hast",
            "Hai",

            "won",
            "gagné",
            "ganado",
            "venceu",
            "gewonnen",
            "vinto",

            "loose",
            "perdu",
            "sueltaste",
            "soltou",
            "dich gelöst",
            "sciolto",

            "AI",
            "IA",
            "IA",
            "AI",
            "KI",
            "IA",

            "Music",
            "Musique",
            "Música",
            "Música",
            "Musik",
            "Musica",

            "Effects",
            "Effets",
            "Efectos",
            "Efeitos",
            "Auswirkungen",
            "Effetti",

            "Number of character",
            "Nombre de caractères",
            "Número de carácter",
            "Número de Caráter",
            "Anzahl der Buchstaben Zeichen",
            "Numero di caratteri lettere",

            "Next",
            "Suivant",
            "Siguiente",
            "Próximo",
            "Nächster",
            "Il prossimo",

            "Finish",
            "Terminer",
            "Terminar",
            "Terminar",
            "Fertig",
            "Finire",

            "Picture",
            "Image",
            "Imagen",
            "Cenário",
            "Bild",
            "Immagine",

            "Color",
            "Couleur",
            "Color",
            "Cor",
            "Farbe",
            "Colore",

            "Infos",
            "Infos",
            "Información",
            "Informações",
            "Die Info",
            "Informazioni",

            "Flag",
            "Drapeau",
            "Bandera",
            "Bandeira",
            "Flagge",
            "Bandiera",

            "Your username must be at least 3 characters long",
            "Votre pseudo doit faire au moins 3 caractères",
            "Su nombre de usuario debe tener al menos 3 caracteres",
            "Seu nome de usuário deve ter pelo menos 3 caracteres",
            "Ihr Benutzername muss mindestens 3 Zeichen lang sein",
            "Il tuo nome utente deve contenere almeno 3 caratteri",

            "Your country must be valid",
            "Votre pays doit être valide",
            "Tu país debe ser válido",
            "Seu país deve ser válido",
            "Ihr Land muss gültig sein",
            "Il tuo paese deve essere valido",

            "Failed, please check the status of your internet connection",
            "Echec, veuillez vérifier l'état votre connection internet",
            "Falló, verifique el estado de su conexión a Internet",
            "Falha, verifique o estado da sua ligação à Internet",
            "Wenn dies fehlgeschlagen ist, überprüfen Sie bitte den Status Ihrer Internetverbindung",
            "Non riuscito, controlla lo stato della tua connessione Internet",

            "ARRAY_END"

        };

    return langStrings[target];
}

char *getCountryString(int target)
{

    char *const countryStrings[] =
        {
            "afghanistan",
            "afghanistan",
            "afganistán",
            "afeganistão",
            "afghanistan",
            "afghanistan",

            "albania",
            "albanie",
            "albania",
            "albânia",
            "albanien",
            "albania",

            "algeria",
            "algérie",
            "argelia",
            "argélia",
            "algerien",
            "algeria",

            "andorra",
            "andorre",
            "andorra",
            "andorra",
            "andorra",
            "andorra",

            "angola",
            "angola",
            "angola",
            "angola",
            "angola",
            "angola",

            "antigua and barbuda",
            "antigua-et-barbuda",
            "antigua y barbuda",
            "antigua e barbuda",
            "antigua und barbuda",
            "antigua e barbuda",

            "argentina",
            "argentine",
            "argentina",
            "argentina",
            "argentinien",
            "argentina",

            "armenia",
            "arménie",
            "armenia",
            "armênia",
            "armenien",
            "armenia",

            "australia",
            "australie",
            "australia",
            "austrália",
            "australien",
            "australia",

            "austria",
            "autriche",
            "austria",
            "áustria",
            "österreich",
            "austria",

            "azerbaijan",
            "azerbaïdjan",
            "azerbaiyán",
            "azerbaijão",
            "aserbaidschan",
            "azerbaigian",

            "bahamas",
            "bahamas",
            "bahamas",
            "bahamas",
            "bahamas",
            "bahamas",

            "bahrain",
            "bahreïn",
            "bahrein",
            "bahrein",
            "bahrain",
            "bahrein",

            "bangladesh",
            "bangladesh",
            "bangladesh",
            "bangladesh",
            "bangladesch",
            "bangladesh",

            "barbados",
            "barbade",
            "barbados",
            "barbados",
            "barbados",
            "barbados",

            "belarus",
            "biélorussie",
            "bielorrusia",
            "bielorrússia",
            "weißrussland",
            "bielorussia",

            "belgium",
            "belgique",
            "bélgica",
            "bélgica",
            "belgien",
            "belgio",

            "belize",
            "belize",
            "belice",
            "belize",
            "belize",
            "belize",

            "benin",
            "bénin",
            "benin",
            "benin",
            "benin",
            "benin",

            "bhutan",
            "bhoutan",
            "bután",
            "butão",
            "bhutan",
            "bhutan",

            "bosnia and herzegovina",
            "bosnie herzégovine",
            "bosnia y herzegovina",
            "bósnia e herzegovina",
            "bosnien und herzegowina",
            "bosnia erzegovina",

            "botswana",
            "botswana",
            "botswana",
            "botswana",
            "botswana",
            "botswana",

            "brazil",
            "brésil",
            "brasil",
            "brasil",
            "brasilien",
            "brasile",

            "brunei",
            "brunei",
            "brunei",
            "brunei",
            "brunei",
            "brunei",

            "bulgaria",
            "bulgarie",
            "bulgaria",
            "bulgária",
            "bulgarien",
            "bulgaria",

            "burkina faso",
            "burkina faso",
            "burkina faso",
            "burkina faso",
            "burkina faso",
            "burkina faso",

            "burundi",
            "burundi",
            "burundi",
            "burundi",
            "burundi",
            "burundi",

            "cambodia",
            "cambodge",
            "camboya",
            "camboja",
            "kambodscha",
            "cambogia",

            "cameroon",
            "cameroun",
            "camerún",
            "camarões",
            "kamerun",
            "camerun",

            "canada",
            "canada",
            "canadá",
            "canadá",
            "kanada",
            "canada",

            "cape verde",
            "cap-vert",
            "cabo verde",
            "cabo verde",
            "kap verde",
            "capo verde",

            "central african republic",
            "république centrafricaine",
            "república centroafricana",
            "república centro-africana",
            "zentralafrikanische republik",
            "repubblica centrafricana",

            "chad",
            "tchad",
            "chad",
            "chade",
            "tschad",
            "chad",

            "chile",
            "chili",
            "chile",
            "chile",
            "chile",
            "chile",

            "china",
            "chine",
            "china",
            "china",
            "china",
            "cina",

            "colombia",
            "colombie",
            "colombia",
            "colômbia",
            "kolumbien",
            "colombia",

            "comoros",
            "comores",
            "comoras",
            "comores",
            "komoren",
            "comore",

            "costa rica",
            "costa rica",
            "costa rica",
            "costa rica",
            "costa rica",
            "costa rica",

            "cote d ivoire",
            "cote d ivoire",
            "costa de marfil",
            "costa d'ivoire",
            "cote d ivoire",
            "costa d'avorio",

            "croatia",
            "croatie",
            "croacia",
            "croácia",
            "kroatien",
            "croazia",

            "cuba",
            "cuba",
            "cuba",
            "cuba",
            "kuba",
            "cuba",

            "cyprus",
            "chypre",
            "chipre",
            "chipre",
            "zypern",
            "cipro",

            "czech republic",
            "république tchèque",
            "republica checa",
            "república checa",
            "tschechien",
            "repubblica ceca",

            "democratic republic of congo",
            "république démocratique du congo",
            "república democrática del congo",
            "república democrática do congo",
            "demokratische republik kongo",
            "repubblica democratica del congo",

            "denmark",
            "danemark",
            "dinamarca",
            "dinamarca",
            "dänemark",
            "danimarca",

            "djibouti",
            "djibouti",
            "djibouti",
            "djibouti",
            "dschibuti",
            "gibuti",

            "dominica",
            "dominique",
            "dominica",
            "dominica",
            "dominica",
            "dominica",

            "dominican republic",
            "république dominicaine",
            "república dominicana",
            "república dominicana",
            "dominikanische republik",
            "repubblica dominicana",

            "east timor",
            "timor oriental",
            "timor oriental",
            "timor leste",
            "osttimor",
            "timor est",

            "ecuador",
            "equateur",
            "ecuador",
            "equador",
            "ecuador",
            "ecuador",

            "egypt",
            "egypte",
            "egipto",
            "egito",
            "ägypten",
            "egitto",

            "el salvador",
            "le salvador",
            "el salvador",
            "el salvador",
            "el salvador",
            "el salvador",

            "equatorial guinea",
            "guinée équatoriale",
            "guinea ecuatorial",
            "guiné equatorial",
            "äquatorialguinea",
            "guinea equatoriale",

            "eritrea",
            "érythrée",
            "eritrea",
            "eritreia",
            "eritrea",
            "eritrea",

            "estonia",
            "estonie",
            "estonia",
            "estônia",
            "estland",
            "estonia",

            "ethiopia",
            "ethiopie",
            "etiopía",
            "etiópia",
            "äthiopien",
            "etiopia",

            "fiji",
            "fidji",
            "fiji",
            "fiji",
            "fidschi",
            "figi",

            "finland",
            "finlande",
            "finlandia",
            "finlândia",
            "finnland",
            "finlandia",

            "france",
            "france",
            "francia",
            "frança",
            "frankreich",
            "francia",

            "gabon",
            "gabon",
            "gabón",
            "gabão",
            "gabon",
            "gabon",

            "gambia",
            "gambie",
            "gambia",
            "gâmbia",
            "gambia",
            "gambia",

            "georgia",
            "géorgie",
            "georgia",
            "geórgia",
            "georgia",
            "georgia",

            "germany",
            "allemagne",
            "alemania",
            "alemanha",
            "deutschland",
            "germania",

            "ghana",
            "ghana",
            "ghana",
            "gana",
            "ghana",
            "ghana",

            "greece",
            "grèce",
            "grecia",
            "grécia",
            "griechenland",
            "grecia",

            "grenada",
            "grenade",
            "granada",
            "granada",
            "grenada",
            "grenada",

            "guatemala",
            "guatemala",
            "guatemala",
            "guatemala",
            "guatemala",
            "guatemala",

            "guinea bissau",
            "guinée bissau",
            "guinea bissau",
            "guiné-bissau",
            "guinea bissau",
            "guinea bissau",

            "guinea",
            "guinée",
            "guinea",
            "guiné",
            "guinea",
            "guinea",

            "guyana",
            "guyane",
            "guayana",
            "guiana",
            "guyana",
            "guyana",

            "haiti",
            "haïti",
            "haití",
            "haiti",
            "haiti",
            "haiti",

            "honduras",
            "honduras",
            "honduras",
            "honduras",
            "honduras",
            "honduras",

            "hungary",
            "hongrie",
            "hungría",
            "hungria",
            "ungarn",
            "ungheria",

            "iceland",
            "islande",
            "islandia",
            "islândia",
            "island",
            "islanda",

            "india",
            "inde",
            "india",
            "índia",
            "indien",
            "india",

            "indonesia",
            "indonésie",
            "indonesia",
            "indonésia",
            "indonesien",
            "indonesia",

            "iran",
            "iran",
            "irán",
            "iran",
            "iran",
            "iran",

            "iraq",
            "irak",
            "irak",
            "iraque",
            "irak",
            "iraq",

            "ireland",
            "irlande",
            "irlanda",
            "irlanda",
            "irland",
            "irlanda",

            "israel",
            "israël",
            "israel",
            "israel",
            "israel",
            "israele",

            "italy",
            "italie",
            "italia",
            "itália",
            "italien",
            "italia",

            "jamaica",
            "jamaïque",
            "jamaica",
            "jamaica",
            "jamaika",
            "giamaica",

            "japan",
            "japon",
            "japón",
            "japão",
            "japan",
            "giappone",

            "jordan",
            "jordan",
            "jordán",
            "jordânia",
            "jordanien",
            "giordania",

            "kazakhstan",
            "kazakhstan",
            "kazajstán",
            "cazaquistão",
            "kasachstan",
            "kazakistan",

            "kenya",
            "kenya",
            "kenia",
            "quênia",
            "kenia",
            "kenya",

            "kiribati",
            "kiribati",
            "kiribati",
            "kiribati",
            "kiribati",
            "kiribati",

            "kosovo",
            "kosovo",
            "kosovo",
            "kosovo",
            "kosovo",
            "kosovo",

            "kuwait",
            "koweit",
            "kuwait",
            "kuwait",
            "kuwait",
            "kuwait",

            "kyrgyzstan",
            "kirghizistan",
            "kirguistán",
            "quirguistão",
            "kirgisistan",
            "kirghizistan",

            "laos",
            "laos",
            "laos",
            "laos",
            "laos",
            "laos",

            "latvia",
            "lettonie",
            "letonia",
            "letônia",
            "lettland",
            "lettonia",

            "lebanon",
            "liban",
            "líbano",
            "líbano",
            "libanon",
            "libano",

            "lesotho",
            "lesotho",
            "lesoto",
            "lesoto",
            "lesotho",
            "lesotho",

            "liberia",
            "libéria",
            "liberia",
            "libéria",
            "liberia",
            "liberia",

            "libya",
            "libye",
            "libia",
            "líbia",
            "libyen",
            "libia",

            "liechtenstein",
            "liechtenstein",
            "liechtenstein",
            "liechtenstein",
            "liechtenstein",
            "liechtenstein",

            "list-country-script.sh",
            "list-country-script.sh",
            "list-country-script.sh",
            "list-country-script.sh",
            "list-country-script.sh",
            "list-country-script.sh",

            "lithuania",
            "lituanie",
            "lituania",
            "lituânia",
            "litauen",
            "lituania",

            "luxembourg",
            "luxembourg",
            "luxemburgo",
            "luxemburgo",
            "luxemburg",
            "lussemburgo",

            "macedonia",
            "macédoine",
            "macedonia",
            "macedônia",
            "mazedonien",
            "macedonia",

            "madagascar",
            "madagascar",
            "madagascar",
            "madagáscar",
            "madagaskar",
            "madagascar",

            "malawi",
            "malawi",
            "malawi",
            "malawi",
            "malawi",
            "malawi",

            "malaysia",
            "malaisie",
            "malasia",
            "malásia",
            "malaysia",
            "malaysia",

            "maldives",
            "maldives",
            "maldivas",
            "maldivas",
            "malediven",
            "maldive",

            "mali",
            "mali",
            "mali",
            "mali",
            "mali",
            "mali",

            "malta",
            "malte",
            "malta",
            "malta",
            "malta",
            "malta",

            "marshall-islands",
            "iles marshall",
            "islas marshall",
            "ilhas marshall",
            "marshallinseln",
            "isole marshall",

            "mauritania",
            "mauritanie",
            "mauritania",
            "mauritânia",
            "mauretanien",
            "mauritania",

            "mauritius",
            "maurice",
            "mauricio",
            "maurício",
            "mauritius",
            "maurizio",

            "mexico",
            "mexique",
            "mexico",
            "méxico",
            "mexiko",
            "messico",

            "micronesia",
            "micronésie",
            "micronesia",
            "micronésia",
            "mikronesien",
            "micronesia",

            "moldova",
            "moldavie",
            "moldavia",
            "moldova",
            "moldau",
            "moldova",

            "monaco",
            "monaco",
            "mónaco",
            "monaco",
            "monaco",
            "monaco",

            "mongolia",
            "mongolie",
            "mongolia",
            "mongólia",
            "mongolei",
            "mongolia",

            "montenegro",
            "monténégro",
            "montenegro",
            "montenegro",
            "montenegro",
            "montenegro",

            "morocco",
            "maroc",
            "marruecos",
            "marrocos",
            "marokko",
            "marocco",

            "mozambique",
            "mozambique",
            "mozambique",
            "moçambique",
            "mozambique",
            "mozambico",

            "myanmar",
            "myanmar",
            "myanmar",
            "myanmar",
            "myanmar",
            "myanmar",

            "named",
            "nommé",
            "nombrada",
            "nomeado",
            "genannt",
            "di nome",

            "namibia",
            "namibie",
            "namibia",
            "namibia",
            "namibia",
            "namibia",

            "nauru",
            "nauru",
            "nauru",
            "nauru",
            "nauru",
            "nauru",

            "nepal",
            "népal",
            "nepal",
            "nepal",
            "nepal",
            "nepal",

            "netherlands",
            "pays-bas",
            "países bajos",
            "países baixos",
            "niederlande",
            "olanda",

            "new-zealand",
            "nouvelle-zélande",
            "nueva zelanda",
            "nova zelândia",
            "neuseeland",
            "nuova zelanda",

            "nicaragua",
            "nicaragua",
            "nicaragua",
            "nicarágua",
            "nicaragua",
            "nicaragua",

            "niger",
            "niger",
            "níger",
            "níger",
            "niger",
            "niger",

            "nigeria",
            "nigeria",
            "nigeria",
            "nigéria",
            "nigeria",
            "nigeria",

            "niue",
            "niue",
            "niue",
            "niue",
            "niue",
            "niue",

            "north-korea",
            "corée du nord",
            "corea del norte",
            "coreia do norte",
            "nord korea",
            "corea del nord",

            "norway",
            "norvège",
            "noruega",
            "noruega",
            "norwegen",
            "norvegia",

            "oman",
            "oman",
            "omán",
            "omã",
            "oman",
            "oman",

            "pakistan",
            "pakistan",
            "pakistán",
            "paquistão",
            "pakistan",
            "pakistan",

            "palau",
            "palau",
            "palau",
            "palau",
            "palau",
            "palau",

            "panama",
            "panama",
            "panamá",
            "panamá",
            "panama",
            "panama",

            "papua new guinea",
            "papouasie nouvelle guinée",
            "papúa nueva guinea",
            "papua nova guiné",
            "papua neu-guinea",
            "papua nuova guinea",

            "paraguay",
            "paraguay",
            "paraguay",
            "paraguai",
            "paraguay",
            "paraguay",

            "peru",
            "pérou",
            "perú",
            "peru",
            "peru",
            "perù",

            "philippines",
            "philippines",
            "filipinas",
            "filipinas",
            "philippinen",
            "filippine",

            "poland",
            "pologne",
            "polonia",
            "polônia",
            "polen",
            "polonia",

            "portugal",
            "le portugal",
            "portugal",
            "portugal",
            "portugal",
            "portogallo",

            "qatar",
            "qatar",
            "katar",
            "catar",
            "katar",
            "qatar",

            "republic of congo",
            "république du congo",
            "república del congo",
            "república do congo",
            "republik kongo",
            "repubblica del congo",

            "romania",
            "roumanie",
            "rumania",
            "romênia",
            "rumänien",
            "romania",

            "russia",
            "russie",
            "rusia",
            "rússia",
            "russland",
            "russia",

            "rwanda",
            "rwanda",
            "ruanda",
            "ruanda",
            "ruanda",
            "ruanda",

            "saint kitts and nevis",
            "saint-christophe-et-niévès",
            "saint kitts y nevis",
            "santos kitts e nevis",
            "st. kitts und nevis",
            "saint kitts e nevis",

            "saint lucia",
            "sainte-lucie",
            "santa lucía",
            "santa lúcia",
            "heilige lucia",
            "santa lucia",

            "saint vincent and the grenadines",
            "saint-vincent-et-les-grenadines",
            "san vicente y las granadinas",
            "são vicente e granadinas",
            "st. vincent und die grenadinen",
            "saint vincent e le grenadine",

            "samoa",
            "samoa",
            "samoa",
            "samoa",
            "samoa",
            "samoa",

            "san marino",
            "saint marin",
            "san marino",
            "san marino",
            "san marino",
            "san marino",

            "sao tome and principe",
            "sao tome et principe",
            "santo tomé y príncipe",
            "são tomé e príncipe",
            "sao tomé und principe",
            "sao tome e principe",

            "saudi arabia",
            "arabie saoudite",
            "arabia saudita",
            "arábia saudita",
            "saudi arabien",
            "arabia saudita",

            "senegal",
            "sénégal",
            "senegal",
            "senegal",
            "senegal",
            "senegal",

            "serbia",
            "serbie",
            "serbia",
            "sérvia",
            "serbien",
            "serbia",

            "seychelles",
            "les seychelles",
            "seychelles",
            "seychelles",
            "seychellen",
            "seychelles",

            "sierra leone",
            "sierra leone",
            "sierra leona",
            "serra leoa",
            "sierra leone",
            "sierra leone",

            "singapore",
            "singapour",
            "singapur",
            "cingapura",
            "singapur",
            "singapore",

            "slovakia",
            "slovaquie",
            "eslovaquia",
            "eslováquia",
            "slowakei",
            "slovacchia",

            "slovenia",
            "slovénie",
            "eslovenia",
            "eslovênia",
            "slowenien",
            "slovenia",

            "solomon islands",
            "îles salomon",
            "islas salomón",
            "ilhas salomão",
            "salomon-inseln",
            "isole salomone",

            "somalia",
            "somalie",
            "somalia",
            "somália",
            "somalia",
            "somalia",

            "south africa",
            "afrique du sud",
            "sudáfrica",
            "áfrica do sul",
            "südafrika",
            "sud africa",

            "south korea",
            "corée du sud",
            "corea del sur",
            "coreia do sul",
            "südkorea",
            "corea del sud",

            "south sudan",
            "soudan du sud",
            "sudán del sur",
            "sudão do sul",
            "südsudan",
            "sudan del sud",

            "spain",
            "espagne",
            "españa",
            "espanha",
            "spanien",
            "spagna",

            "sri lanka",
            "sri lanka",
            "sri lanka",
            "sri lanka",
            "sri lanka",
            "sri lanka",

            "sudan",
            "soudan",
            "sudán",
            "sudão",
            "sudan",
            "sudan",

            "suriname",
            "suriname",
            "surinam",
            "suriname",
            "suriname",
            "suriname",

            "swaziland",
            "swaziland",
            "swazilandia",
            "suazilândia",
            "swasiland",
            "dello swaziland",

            "sweden",
            "suède",
            "suecia",
            "suécia",
            "schweden",
            "svezia",

            "switzerland",
            "suisse",
            "suiza",
            "suíça",
            "schweiz",
            "svizzera",

            "syria",
            "syrie",
            "siria",
            "síria",
            "syrien",
            "siria",

            "taiwan",
            "taïwan",
            "taiwán",
            "taiwan",
            "taiwan",
            "taiwan",

            "tajikistan",
            "tadjikistan",
            "tayikistán",
            "tajiquistão",
            "tadschikistan",
            "tagikistan",

            "tanzania",
            "tanzanie",
            "tanzania",
            "tanzânia",
            "tansania",
            "tanzania",

            "thailand",
            "thaïlande",
            "tailandia",
            "tailândia",
            "thailand",
            "tailandia",

            "togo",
            "aller",
            "ir",
            "ir",
            "gehen",
            "andare",

            "tonga",
            "tonga",
            "tonga",
            "tonga",
            "tonga",
            "tonga",

            "trinidad and tobago",
            "trinité-et-tobago",
            "trinidad y tobago",
            "trinidad e tobago",
            "trinidad und tobago",
            "trinidad e tobago",

            "tunisia",
            "tunisie",
            "túnez",
            "tunísia",
            "tunesien",
            "tunisia",

            "turkey",
            "dinde",
            "pavo",
            "peru",
            "truthahn",
            "tacchino",

            "turkmenistan",
            "turkménistan",
            "turkmenistán",
            "turcomenistão",
            "turkmenistan",
            "turkmenistan",

            "tuvalu",
            "tuvalu",
            "tuvalu",
            "tuvalu",
            "tuvalu",
            "tuvalu",

            "uganda",
            "ouganda",
            "uganda",
            "uganda",
            "uganda",
            "uganda",

            "ukraine",
            "ukraine",
            "ucrania",
            "ucrânia",
            "ukraine",
            "ucraina",

            "united arab emirates",
            "emirats arabes unis",
            "emiratos árabes unidos",
            "emirados árabes unidos",
            "vereinigte arabische emirate",
            "emirati arabi uniti",

            "united kingdom",
            "royaume-uni",
            "reino unido",
            "reino unido",
            "großbritannien",
            "regno unito",

            "united states of america",
            "les états-unis d'amérique",
            "estados unidos de america",
            "estados unidos da america",
            "vereinigte staaten von amerika",
            "stati uniti d'america",

            "uruguay",
            "uruguay",
            "uruguay",
            "uruguai",
            "uruguay",
            "uruguay",

            "uzbekistan",
            "ouzbékistan",
            "uzbekistán",
            "uzbequistão",
            "usbekistan",
            "uzbekistan",

            "vatican city",
            "cité du vatican",
            "ciudad del vaticano",
            "cidade do vaticano",
            "vatikanstadt",
            "città del vaticano",

            "venezuela",
            "venezuela",
            "venezuela",
            "venezuela",
            "venezuela",
            "venezuela",

            "vietnam",
            "vietnam",
            "vietnam",
            "vietnã",
            "vietnam",
            "vietnam",

            "yemen",
            "yémen",
            "yemen",
            "iémen",
            "jemen",
            "yemen",

            "zambia",
            "zambie",
            "zambia",
            "zâmbia",
            "sambia",
            "zambia",

            "ARRAY_END"};

    return countryStrings[target];
}

#endif